# Generated by Django 3.2.5 on 2022-07-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('park_name', models.CharField(max_length=100)),
                ('park_latitude', models.FloatField()),
                ('park_longitude', models.FloatField()),
            ],
            options={
                'db_table': 'park',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
    ]
